version: '3.4'

x-common-variables: &common-variables
  MYSQL_DATABASE: 'db'
  MYSQL_USER: 'user'
  MYSQL_PASSWORD: 'password'
  MYSQL_ROOT_PASSWORD: 'password'
  MYSQL_PORT: '3307'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      <<: *common-variables
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - mysql-net

volumes:
  mysql-volume:

networks:
  mysql-net:
    driver: bridge